Task 5 from module 7
JMagn/JMagn-kodilla-java pull request #13
Opened 2018-08-22 23:13 UTC by JMagn

2018-08-23 19:18 UTC, xmarcinsx commented on kodilla-stream/src/main/java/com/kodilla/stream/array/ArrayOperations.java
> +        System.out.println("\nAverage: " + avg.getAsDouble());
Stosujesz getAsDouble na czymś, co może nie być w środku optionala, wtedy zostanie rzucony wyjątek.
Proponuję
`OptionalDouble avg = IntStream.range(0, numbers.length)`
`                .map(i -> numbers[i])`
`                .average()`
`                .orElse(0);`

2018-08-23 19:20 UTC, xmarcinsx requested changes
:-1:

2018-08-23 19:20 UTC, xmarcinsx commented on kodilla-stream/src/main/java/com/kodilla/stream/array/ArrayOperations.java
> +        System.out.println("\nAverage: " + avg.getAsDouble());
Zaś wypisanie średniej powinno się odbyć poza tą metodą

2018-08-31 05:40 UTC, mps4dev requested changes
Jest juz okej, z tym, ze w metodzie, ktora jako parametr otrzymuje jakis obiekt (tu tablice) trzeba przeprowadzic walidacje, czy nie przekazano do metody nulla. jesli numbers == null, to przy wywolaniu numbers.length otrzymamy NullPointerException (NPE)

2018-09-04 20:14 UTC, mps4dev approved these changes
👍

2018-09-04 20:38 UTC, merged