Task 6 from module 7
JMagn/JMagn-kodilla-java pull request #14
Opened 2018-08-22 23:14 UTC by JMagn

2018-08-23 19:30 UTC, xmarcinsx requested changes
:-1:

2018-08-23 19:30 UTC, xmarcinsx commented on kodilla-stream/src/main/java/com/kodilla/stream/portfolio/Task.java
> +    }
brak equals i hashCode

2018-08-23 19:30 UTC, xmarcinsx commented on kodilla-stream/src/main/java/com/kodilla/stream/portfolio/TaskList.java
> +    }
brak hashCode

2018-08-23 19:30 UTC, xmarcinsx commented on kodilla-stream/src/main/java/com/kodilla/stream/portfolio/User.java
> +    }
brak hashCode

2018-08-23 19:30 UTC, xmarcinsx commented on kodilla-stream/src/test/java/com/kodilla/stream/portfolio/BoardTestSuite.java
> +                .reduce(0, (all, current) -> all += current);
te dwa streamy są bardzo podobne do siebie :) Można użyć jednego streamu z użyciem Collectors.summarizingInt()

2018-08-30 20:43 UTC, JMagn commented on kodilla-stream/src/main/java/com/kodilla/stream/portfolio/Task.java
> +    }
Klasy Task, TaskList, User i Board nie były robione przeze mnie. Są przekopiowane z kursu gdzie w ten sposób kazali je przygotować przed zadaniem. Sam się zastanawiałem czemu tak ;)

2018-09-04 20:18 UTC, mps4dev approved these changes
👍

2018-09-04 20:41 UTC, merged