Task 5 from module 6
JMagn/JMagn-kodilla-java pull request #5
Opened 2018-07-28 13:03 UTC by JMagn

2018-07-28 16:44 UTC, mps4dev requested changes
👎

2018-07-28 16:44 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/ForumStatisctics.java
> +        if (usersNumber > 0) {
czy wszystkie operacje musza byc w if?

2018-07-28 16:44 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/ForumStatisctics.java
> +            this.commentsNumber = statistics.commentsCount();
j.w.

2018-07-28 16:44 UTC, mps4dev commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/ForumStatisctics.java
> +        return usersNumber;
a gdzie pozostale gettery?

2018-07-28 16:44 UTC, mps4dev commented on kodilla-testing/src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestSuite.java
> +        Statistics statisticsMock = mock(Statistics.class);
uzyj @Before

2018-07-28 17:22 UTC, JMagn commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/ForumStatisctics.java
> +        if (usersNumber > 0) {
Wrzuciłem wszystko w if bo uznałem, że jeśli userów będzie zero to postów i komentarzy też z automatu powinno być zero. Tak samo w przypadku zera postów > nie będzie komentarzy. Mam to poprawić?

2018-07-28 17:24 UTC, JMagn commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/ForumStatisctics.java
> +        return usersNumber;
Myślałem, że mają być tylko te wymagane w testach.

2018-07-30 06:30 UTC, mps4dev approved these changes
👍

2018-07-30 12:28 UTC, merged